name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update submodules
        run: |
          git submodule update --init --recursive
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - name: Build with Maven
        run: ./mvnw --batch-mode --no-transfer-progress verify --file pom.xml

      - name: Upload playlist
        uses: actions/upload-artifact@v3
        with:
          name: Upload playlist
          path: |
            playlist.xml